//! Top-level Dioxus application shell.
//!
//! v0.1 responsibilities:
//! - Mount the Tailwind stylesheet.
//! - Detect File System Access API support; show the unsupported-browser
//!   gate (D5) when missing and skip the canvas entirely.
//! - When supported, render the toolbar (`Open`, `Save`) and the two
//!   stacked canvases that `capture` and `render` will own.
//!
//! Capture, render, and persist modules wire up in subsequent steps.
//! The shell deliberately does the minimum needed to prove the
//! pipeline (Dioxus + Tailwind + WASM in the browser) before those
//! modules land.

use dioxus::prelude::*;

/// Tailwind output, regenerated by `tools/tailwindcss.exe -i
/// assets/tailwind.css -o assets/output.css`. Must exist on disk at
/// compile time — the `asset!` macro validates its presence.
const TAILWIND_CSS: Asset = asset!("/assets/output.css");

/// Root component. Mounts the stylesheet and dispatches between the
/// supported-browser app surface and the unsupported-browser gate.
#[component]
pub fn App() -> Element {
    let supported = is_fsa_supported();

    rsx! {
        document::Stylesheet { href: TAILWIND_CSS }

        if supported {
            SupportedShell {}
        } else {
            UnsupportedGate {}
        }
    }
}

/// Toolbar + canvas mount points. The canvases are claimed by
/// `render` / `capture` after mount; Dioxus does not manage their
/// pixels (D6).
#[component]
fn SupportedShell() -> Element {
    rsx! {
        div { class: "flex flex-col h-screen w-screen bg-white",
            // Toolbar.
            div { class: "flex items-center gap-2 px-3 py-2 border-b border-gray-200",
                button {
                    class: "px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 \
                            text-gray-800 text-sm font-medium",
                    // Wired in the persist step.
                    disabled: true,
                    "Open"
                }
                button {
                    class: "px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 \
                            text-gray-800 text-sm font-medium",
                    // Wired in the persist step.
                    disabled: true,
                    "Save"
                }
                span { class: "ml-auto text-xs text-gray-400",
                    "Stroke v0.1 — scaffold"
                }
            }

            // Canvas stack. The two <canvas> elements live in the same
            // grid cell so they overlap perfectly; the live canvas
            // sits visually above the committed canvas. CSS
            // `pointer-events: none` on the live canvas (set in the
            // render module when it claims the element) lets input
            // pass through to the layer below.
            div { class: "relative flex-1 overflow-hidden",
                canvas {
                    id: "stroke-committed",
                    class: "absolute inset-0 w-full h-full",
                }
                canvas {
                    id: "stroke-live",
                    class: "absolute inset-0 w-full h-full pointer-events-none",
                }
            }
        }
    }
}

/// Unsupported-browser gate (D5). Single message; nothing else
/// renders — no canvas, no toolbar.
#[component]
fn UnsupportedGate() -> Element {
    rsx! {
        div { class: "flex h-screen w-screen items-center justify-center bg-white",
            div { class: "max-w-md text-center px-6",
                h1 { class: "text-xl font-semibold text-gray-800 mb-2",
                    "Unsupported browser"
                }
                p { class: "text-sm text-gray-600",
                    "Stroke v0.1 requires the File System Access API. \
                     Please open this app in a Chromium-based browser \
                     (Chrome, Edge, or equivalent)."
                }
            }
        }
    }
}

/// Returns `true` when `window.showSaveFilePicker` is defined.
///
/// This is the v0.1 capability gate: full FSA support is required
/// (D5). We probe a single function; the rest of the API ships
/// together in every browser that has it.
fn is_fsa_supported() -> bool {
    let Some(window) = web_sys::window() else {
        return false;
    };
    let value = js_sys::Reflect::get(&window, &"showSaveFilePicker".into())
        .unwrap_or(wasm_bindgen::JsValue::UNDEFINED);
    value.is_function()
}
