//! Top-level Dioxus application shell.
//!
//! v0.1 responsibilities:
//! - Mount the Tailwind stylesheet.
//! - Detect File System Access API support; show the unsupported-browser
//!   gate (D5) when missing and skip the canvas entirely.
//! - When supported, render the toolbar (`Open`, `Save`) and the two
//!   stacked canvases that `capture` and `render` will own.
//!
//! Capture, render, and persist modules wire up in subsequent steps.
//! The shell deliberately does the minimum needed to prove the
//! pipeline (Dioxus + Tailwind + WASM in the browser) before those
//! modules land.

use std::cell::RefCell;
use std::rc::Rc;

use dioxus::prelude::*;
use wasm_bindgen::closure::Closure;
use wasm_bindgen::JsCast;

use crate::capture;
use crate::document::{Canvas, Document};
use crate::persist::{self, PersistError};
use crate::render;

/// Tailwind output, regenerated by `tools/tailwindcss.exe -i
/// assets/tailwind.css -o assets/output.css`. Must exist on disk at
/// compile time — the `asset!` macro validates its presence.
const TAILWIND_CSS: Asset = asset!("/assets/output.css");

/// Root component. Mounts the stylesheet and dispatches between the
/// supported-browser app surface and the unsupported-browser gate.
#[component]
pub fn App() -> Element {
    let supported = is_fsa_supported();

    rsx! {
        document::Stylesheet { href: TAILWIND_CSS }

        if supported {
            SupportedShell {}
        } else {
            UnsupportedGate {}
        }
    }
}

/// Toolbar + canvas mount points. The canvases are claimed by
/// `render` / `capture` after mount; Dioxus does not manage their
/// pixels (D6).
#[component]
fn SupportedShell() -> Element {
    // Document state lives outside Dioxus's reactive system because
    // the capture / render hot path must not trigger re-renders.
    // The dirty flag is a signal so the toolbar can react to it.
    let dirty = use_signal(|| false);

    // Wire renderer + capture + persist once after the canvases
    // exist in the DOM. Empty dependency list → runs after first
    // paint, never again. The document and dirty handle are
    // captured by `move` and persist for the lifetime of the page.
    use_effect(move || {
        if let Err(err) = render::init() {
            web_sys::console::error_1(&format!("render::init failed: {err}").into());
            return;
        }

        // Initial canvas size for the document is the live canvas's
        // CSS size at mount time. Sufficient for v0.1 (no resize
        // handling). The exact value is not load-bearing — it only
        // declares the coordinate frame for the file format.
        let (w, h) = canvas_css_size("stroke-committed").unwrap_or((1280.0, 800.0));
        let doc = Rc::new(RefCell::new(Document::new(1, Canvas::css_px(w, h))));

        // `Signal` is `Copy`; we can call `.set` from a `Fn` closure
        // by moving the (copied) signal handle into it.
        let dirty_handle = dirty;
        if let Err(err) = capture::init(doc.clone(), move || dirty_handle.clone().set(true)) {
            web_sys::console::error_1(&format!("capture::init failed: {err}").into());
        }

        persist::init(doc);

        // beforeunload guard (D5). The browser only honors the
        // prompt when the listener sets `returnValue` to a
        // non-empty string AND calls `preventDefault`. The exact
        // string is ignored by modern browsers but must be
        // non-empty. We register the listener once and let it
        // re-read the live dirty state on every fire.
        install_beforeunload_guard(dirty);
    });

    rsx! {
        div { class: "flex flex-col h-screen w-screen bg-white",
            // Toolbar.
            div { class: "flex items-center gap-2 px-3 py-2 border-b border-gray-200",
                button {
                    class: "px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 \
                            text-gray-800 text-sm font-medium",
                    onclick: move |_| {
                        // Confirm-discard prompt when there are
                        // unsaved changes (D5). If the user dismisses
                        // the prompt we do not even open the picker.
                        if dirty() && !confirm_discard() {
                            return;
                        }
                        // `Signal: Copy`; rebind locally so we can
                        // call `set` (which needs `&mut self`) from
                        // inside this `Fn`-typed handler.
                        let mut dirty = dirty;
                        spawn(async move {
                            match persist::open().await {
                                Ok(()) => dirty.set(false),
                                Err(PersistError::Cancelled) => {}
                                Err(err) => report_persist_error("open", err),
                            }
                        });
                    },
                    "Open"
                }
                button {
                    class: "px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 \
                            text-gray-800 text-sm font-medium",
                    onclick: move |_| {
                        let mut dirty = dirty;
                        spawn(async move {
                            match persist::save().await {
                                Ok(()) => dirty.set(false),
                                Err(PersistError::Cancelled) => {}
                                Err(err) => report_persist_error("save", err),
                            }
                        });
                    },
                    "Save"
                }
                span { class: "ml-auto text-xs text-gray-400",
                    if dirty() { "Stroke v0.1 — unsaved changes" } else { "Stroke v0.1 — scaffold" }
                }
            }

            // Canvas stack. The two <canvas> elements live in the same
            // grid cell so they overlap perfectly; the live canvas
            // sits visually above the committed canvas. CSS
            // `pointer-events: none` on the live canvas (set in the
            // render module when it claims the element) lets input
            // pass through to the layer below.
            div { class: "relative flex-1 overflow-hidden",
                canvas {
                    id: "stroke-committed",
                    class: "absolute inset-0 w-full h-full",
                }
                canvas {
                    id: "stroke-live",
                    class: "absolute inset-0 w-full h-full pointer-events-none",
                }
            }
        }
    }
}

/// Unsupported-browser gate (D5). Single message; nothing else
/// renders — no canvas, no toolbar.
#[component]
fn UnsupportedGate() -> Element {
    rsx! {
        div { class: "flex h-screen w-screen items-center justify-center bg-white",
            div { class: "max-w-md text-center px-6",
                h1 { class: "text-xl font-semibold text-gray-800 mb-2",
                    "Unsupported browser"
                }
                p { class: "text-sm text-gray-600",
                    "Stroke v0.1 requires the File System Access API. \
                     Please open this app in a Chromium-based browser \
                     (Chrome, Edge, or equivalent)."
                }
            }
        }
    }
}

/// Returns `true` when `window.showSaveFilePicker` is defined.
///
/// This is the v0.1 capability gate: full FSA support is required
/// (D5). We probe a single function; the rest of the API ships
/// together in every browser that has it.
fn is_fsa_supported() -> bool {
    let Some(window) = web_sys::window() else {
        return false;
    };
    let value = js_sys::Reflect::get(&window, &"showSaveFilePicker".into())
        .unwrap_or(wasm_bindgen::JsValue::UNDEFINED);
    value.is_function()
}

/// Returns the CSS-pixel size of the canvas element with the given
/// id, if it can be located. Used at app startup to seed the
/// document's coordinate frame (D3) with the actual rendered size
/// of the drawing surface.
fn canvas_css_size(id: &str) -> Option<(f64, f64)> {
    let canvas = web_sys::window()?.document()?.get_element_by_id(id)?;
    Some((canvas.client_width() as f64, canvas.client_height() as f64))
}

/// Installs a `beforeunload` listener that prompts the user when
/// there are unsaved changes (D5). The browser's native dialog is
/// the only thing that can intercept tab-close; modern browsers
/// ignore custom messages but require `returnValue` to be set.
///
/// The closure is intentionally leaked: it must outlive every
/// possible unload event, which means the lifetime of the page.
fn install_beforeunload_guard(dirty: Signal<bool>) {
    let Some(window) = web_sys::window() else {
        return;
    };
    let closure = Closure::wrap(Box::new(move |event: web_sys::BeforeUnloadEvent| {
        if dirty() {
            event.prevent_default();
            event.set_return_value("");
        }
    }) as Box<dyn FnMut(web_sys::BeforeUnloadEvent)>);
    let _ =
        window.add_event_listener_with_callback("beforeunload", closure.as_ref().unchecked_ref());
    // Leak: the listener must live for the page's lifetime. Storing
    // it elsewhere would only delay the same outcome.
    closure.forget();
}

/// Synchronous `window.confirm` prompt for the discard-unsaved
/// flow on Open (D5). Returns `true` if the user accepted.
fn confirm_discard() -> bool {
    web_sys::window()
        .and_then(|w| {
            w.confirm_with_message("Discard unsaved changes and open another file?")
                .ok()
        })
        .unwrap_or(false)
}

/// Logs persistence errors to the console. v0.1 does not surface a
/// toast or modal — the spec calls only for "an error message", and
/// the dev console is the agreed channel until a UI affordance is
/// added.
fn report_persist_error(op: &str, err: PersistError) {
    web_sys::console::error_1(&format!("persist::{op} failed: {err}").into());
}
