//! Top-level Dioxus application shell.
//!
//! v0.2 responsibilities:
//! - Mount the Tailwind stylesheet.
//! - Detect File System Access API support; show the unsupported-browser
//!   gate (D5) when missing and skip the canvas entirely.
//! - When supported, render the toolbar (`New`, `Open`, `Save`, `Save As`)
//!   and the two
//!   stacked canvases that `capture` and `render` will own.
//!
//! Capture, render, history, and persist stay behind narrow module APIs so the
//! Dioxus shell can own commands and visible status without owning canvas
//! pixels.

use std::cell::RefCell;
use std::rc::Rc;

use dioxus::prelude::*;
use wasm_bindgen::closure::Closure;
use wasm_bindgen::JsCast;

use crate::capture;
use crate::document::{Canvas, Document, DocumentError};
use crate::history::StrokeHistory;
use crate::persist::{self, PersistError};
use crate::render;

/// Tailwind output, regenerated by `tools/tailwindcss.exe -i
/// assets/tailwind.css -o assets/output.css`. Must exist on disk at
/// compile time — the `asset!` macro validates its presence.
const TAILWIND_CSS: Asset = asset!("/assets/output.css");

/// Root component. Mounts the stylesheet and dispatches between the
/// supported-browser app surface and the unsupported-browser gate.
#[component]
pub fn App() -> Element {
    let supported = is_fsa_supported();

    rsx! {
        document::Stylesheet { href: TAILWIND_CSS }

        if supported {
            SupportedShell {}
        } else {
            UnsupportedGate {}
        }
    }
}

/// Toolbar + canvas mount points. The canvases are claimed by
/// `render` / `capture` after mount; Dioxus does not manage their
/// pixels (D6).
#[component]
fn SupportedShell() -> Element {
    // Document state lives outside Dioxus's reactive system because
    // the capture / render hot path must not trigger re-renders.
    // Dirty / file / error state are signals so the toolbar can react to them.
    let document = use_hook(|| {
        Rc::new(RefCell::new(Document::new(
            1,
            Canvas::css_px(1280.0, 800.0),
        )))
    });
    let history = use_hook(|| Rc::new(RefCell::new(StrokeHistory::new())));
    let dirty = use_signal(|| false);
    let current_file = use_signal(|| None::<String>);
    let persist_error = use_signal(|| None::<String>);
    let status_text = {
        let is_dirty = dirty();
        match current_file() {
            Some(file_name) if is_dirty => format!("Stroke v0.2 - dirty - {file_name}"),
            Some(file_name) => format!("Stroke v0.2 - saved - {file_name}"),
            None => "Stroke v0.2 - unsaved new document".to_string(),
        }
    };

    // Wire renderer + capture + persist once the canvas's parent container has
    // actually been laid out. `render::init` owns ongoing resize observation;
    // this startup wait only avoids claiming the canvas before flex layout has
    // produced a meaningful first box.
    let document_for_effect = document.clone();
    let history_for_effect = history.clone();
    use_effect(move || {
        let dirty_handle = dirty;
        let document = document_for_effect.clone();
        let history = history_for_effect.clone();
        wait_for_layout_then(move || {
            if let Err(err) = render::init(document.clone()) {
                web_sys::console::error_1(&format!("render::init failed: {err}").into());
                return;
            }
            let (w, h) = render::current_css_size().unwrap_or((1280.0, 800.0));
            *document.borrow_mut() = Document::new(1, Canvas::css_px(w, h));

            // `Signal` is `Copy`; we can call `.set` from a `Fn`
            // closure by moving the (copied) signal handle into it.
            let history_for_capture = history.clone();
            if let Err(err) = capture::init(document.clone(), move || {
                history_for_capture.borrow_mut().record_new_stroke();
                dirty_handle.clone().set(true);
            }) {
                web_sys::console::error_1(&format!("capture::init failed: {err}").into());
            }

            persist::init(document.clone());
            install_keyboard_shortcuts(document.clone(), history.clone(), dirty_handle);

            // beforeunload guard (D5). The browser only honors the
            // prompt when the listener sets `returnValue` to a
            // non-empty string AND calls `preventDefault`. The
            // exact string is ignored by modern browsers but must
            // be non-empty. We register the listener once and let
            // it re-read the live dirty state on every fire.
            install_beforeunload_guard(dirty_handle);
        });
    });

    rsx! {
        div { class: "flex flex-col h-screen w-screen bg-white",
            // Toolbar.
            div { class: "flex items-center gap-2 px-3 py-2 border-b border-gray-200 shrink-0",
                button {
                    class: "px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 \
                            text-gray-800 text-sm font-medium",
                    onclick: {
                        let document = document.clone();
                        let history = history.clone();
                        move |_| {
                            if *dirty.peek()
                                && !confirm_discard("Discard unsaved changes and create a new document?")
                            {
                                return;
                            }
                            create_new_document(
                                document.clone(),
                                history.clone(),
                                dirty,
                                current_file,
                                persist_error,
                            );
                        }
                    },
                    "New"
                }
                button {
                    class: "px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 \
                            text-gray-800 text-sm font-medium",
                    onclick: {
                        let history = history.clone();
                        move |_| {
                        if *dirty.peek()
                            && !confirm_discard("Discard unsaved changes and open another file?")
                        {
                            return;
                        }
                        let mut dirty = dirty;
                        let mut current_file = current_file;
                        let mut persist_error = persist_error;
                        let history = history.clone();
                        spawn(async move {
                            match persist::open().await {
                                Ok(file_name) => {
                                    history.borrow_mut().clear();
                                    dirty.set(false);
                                    current_file.set(Some(file_name));
                                    persist_error.set(None);
                                }
                                Err(PersistError::Cancelled) => {}
                                Err(err) => {
                                    persist_error.set(Some(persist_error_message("Open", err)));
                                }
                            }
                        });
                        }
                    },
                    "Open"
                }
                button {
                    class: "px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 \
                            text-gray-800 text-sm font-medium",
                    onclick: move |_| {
                        let mut dirty = dirty;
                        let mut current_file = current_file;
                        let mut persist_error = persist_error;
                        spawn(async move {
                            match persist::save().await {
                                Ok(file_name) => {
                                    dirty.set(false);
                                    current_file.set(Some(file_name));
                                    persist_error.set(None);
                                }
                                Err(PersistError::Cancelled) => {}
                                Err(err) => {
                                    dirty.set(true);
                                    persist_error.set(Some(persist_error_message("Save", err)));
                                }
                            }
                        });
                    },
                    "Save"
                }
                button {
                    class: "px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 \
                            text-gray-800 text-sm font-medium",
                    onclick: move |_| {
                        let mut dirty = dirty;
                        let mut current_file = current_file;
                        let mut persist_error = persist_error;
                        spawn(async move {
                            match persist::save_as().await {
                                Ok(file_name) => {
                                    dirty.set(false);
                                    current_file.set(Some(file_name));
                                    persist_error.set(None);
                                }
                                Err(PersistError::Cancelled) => {}
                                Err(err) => {
                                    dirty.set(true);
                                    persist_error.set(Some(persist_error_message("Save As", err)));
                                }
                            }
                        });
                    },
                    "Save As"
                }
                span {
                    class: "ml-auto min-w-0 max-w-[45vw] truncate text-xs text-gray-500",
                    title: "{status_text}",
                    "{status_text}"
                }
            }

            if let Some(message) = persist_error() {
                div { class: "flex items-center gap-3 px-3 py-2 border-b border-red-200 bg-red-50 text-sm text-red-800 shrink-0",
                    span { class: "min-w-0 flex-1", "{message}" }
                    button {
                        class: "px-2 py-1 rounded bg-white hover:bg-red-100 text-red-800 text-xs font-medium border border-red-200",
                        onclick: move |_| {
                            let mut persist_error = persist_error;
                            persist_error.set(None);
                        },
                        "Dismiss"
                    }
                }
            }

            // Canvas stack. The two <canvas> elements live in the same
            // grid cell so they overlap perfectly; the live canvas
            // sits visually above the committed canvas. CSS
            // `pointer-events: none` on the live canvas (set in the
            // render module when it claims the element) lets input
            // pass through to the layer below.
            div { class: "relative flex-1 overflow-hidden",
                canvas {
                    id: "stroke-committed",
                    class: "absolute inset-0 w-full h-full",
                }
                canvas {
                    id: "stroke-live",
                    class: "absolute inset-0 w-full h-full pointer-events-none",
                }
            }
        }
    }
}

/// Unsupported-browser gate (D5). Single message; nothing else
/// renders — no canvas, no toolbar.
#[component]
fn UnsupportedGate() -> Element {
    rsx! {
        div { class: "flex h-screen w-screen items-center justify-center bg-white",
            div { class: "max-w-md text-center px-6",
                h1 { class: "text-xl font-semibold text-gray-800 mb-2",
                    "Unsupported browser"
                }
                p { class: "text-sm text-gray-600",
                    "Stroke v0.2 requires the File System Access API. \
                     Please open this app in a Chromium-based browser \
                     (Chrome, Edge, or equivalent)."
                }
            }
        }
    }
}

/// Returns `true` when `window.showSaveFilePicker` is defined.
///
/// This is the v0.2 capability gate: full FSA support is required
/// (D5). We probe a single function; the rest of the API ships
/// together in every browser that has it.
fn is_fsa_supported() -> bool {
    let Some(window) = web_sys::window() else {
        return false;
    };
    let value = js_sys::Reflect::get(&window, &"showSaveFilePicker".into())
        .unwrap_or(wasm_bindgen::JsValue::UNDEFINED);
    value.is_function()
}

/// Returns the CSS-pixel size of the parent of the canvas element
/// with the given id, if it can be located. We measure the parent
/// (the flex container) rather than the canvas because the
/// canvas's own `getBoundingClientRect` can be unreliable during
/// the first paint pass — see `render::init` for the same trick.
fn canvas_css_size(id: &str) -> Option<(f64, f64)> {
    let canvas = web_sys::window()?.document()?.get_element_by_id(id)?;
    let parent = canvas.parent_element()?;
    let rect = parent.get_bounding_client_rect();
    Some((rect.width(), rect.height()))
}

/// Schedules `init` to run as soon as the canvas's parent
/// container has reached a realistic size, polling on
/// `requestAnimationFrame`.
///
/// We need to defer initialization until layout is settled so the
/// renderer can size the canvas bitmap to the actual CSS box. A
/// single rAF after `use_effect` is not always enough: Dioxus + the
/// browser sometimes report the flex parent at a stub size on the
/// first frame and only expand it on a subsequent frame.
///
/// We give up after `MAX_FRAMES` frames and proceed anyway. That
/// is a defensive limit, not an expected path; if it ever fires
/// the user will see a misaligned cursor and we will hear about it.
/// Sub-100ms cap so the user notices the delay only as a single
/// pre-paint pause, not as a hung canvas.
fn wait_for_layout_then(init: impl FnOnce() + 'static) {
    /// Maximum number of animation frames we will wait. At ~60Hz
    /// this is roughly 100ms of wall-clock time.
    const MAX_FRAMES: u32 = 6;
    /// Minimum CSS-pixel height we treat as "laid out". Anything
    /// less suggests the flex parent has not expanded yet — the
    /// HTML default canvas is 150px tall, so we set the bar
    /// comfortably above that.
    const MIN_HEIGHT: f64 = 200.0;

    let Some(window) = web_sys::window() else {
        init();
        return;
    };

    // Type aliases keep clippy happy and call sites readable.
    type InitCell = Rc<RefCell<Option<Box<dyn FnOnce()>>>>;
    type ClosureCell = Rc<RefCell<Option<Closure<dyn FnMut()>>>>;

    // Shared cell so the rAF closure can re-arm itself.
    let init_cell: InitCell = Rc::new(RefCell::new(Some(Box::new(init))));
    let frames_left = Rc::new(RefCell::new(MAX_FRAMES));
    let closure_holder: ClosureCell = Rc::new(RefCell::new(None));

    let window_cl = window.clone();
    let init_cell_cl = init_cell.clone();
    let frames_left_cl = frames_left.clone();
    let closure_holder_cl = closure_holder.clone();

    let closure = Closure::wrap(Box::new(move || {
        let height = canvas_css_size("stroke-committed")
            .map(|(_, h)| h)
            .unwrap_or(0.0);
        let mut remaining = frames_left_cl.borrow_mut();

        if height >= MIN_HEIGHT || *remaining == 0 {
            // Drop our self-reference and run init exactly once.
            // Drop the closure handle first so we are not holding
            // it across the user-supplied init call.
            let _ = closure_holder_cl.borrow_mut().take();
            if let Some(init) = init_cell_cl.borrow_mut().take() {
                init();
            }
            return;
        }

        *remaining -= 1;
        if let Some(closure) = closure_holder_cl.borrow().as_ref() {
            let _ = window_cl.request_animation_frame(closure.as_ref().unchecked_ref());
        }
    }) as Box<dyn FnMut()>);

    let _ = window.request_animation_frame(closure.as_ref().unchecked_ref());
    *closure_holder.borrow_mut() = Some(closure);
}

/// Installs a `beforeunload` listener that prompts the user when
/// there are unsaved changes (D5). The browser's native dialog is
/// the only thing that can intercept tab-close; modern browsers
/// ignore custom messages but require `returnValue` to be set.
fn install_beforeunload_guard(dirty: Signal<bool>) {
    let Some(window) = web_sys::window() else {
        return;
    };
    let closure = Closure::wrap(Box::new(move |event: web_sys::BeforeUnloadEvent| {
        if *dirty.peek() {
            event.prevent_default();
            event.set_return_value("");
        }
    }) as Box<dyn FnMut(web_sys::BeforeUnloadEvent)>);
    let _ =
        window.add_event_listener_with_callback("beforeunload", closure.as_ref().unchecked_ref());
    // Leak: the listener must live for the page's lifetime. Storing
    // it elsewhere would only delay the same outcome.
    closure.forget();
}

/// Replace the current document with a blank unsaved one.
fn create_new_document(
    document: Rc<RefCell<Document>>,
    history: Rc<RefCell<StrokeHistory>>,
    mut dirty: Signal<bool>,
    mut current_file: Signal<Option<String>>,
    mut persist_error: Signal<Option<String>>,
) {
    let (w, h) = render::current_css_size().unwrap_or((1280.0, 800.0));
    *document.borrow_mut() = Document::new(1, Canvas::css_px(w, h));
    history.borrow_mut().clear();
    persist::forget_handle();
    {
        let doc = document.borrow();
        render::repaint_committed(&doc);
    }
    dirty.set(false);
    current_file.set(None);
    persist_error.set(None);
}

/// Installs document-level keyboard shortcuts for stroke history.
fn install_keyboard_shortcuts(
    document: Rc<RefCell<Document>>,
    history: Rc<RefCell<StrokeHistory>>,
    mut dirty: Signal<bool>,
) {
    let Some(window) = web_sys::window() else {
        return;
    };
    let closure = Closure::wrap(Box::new(move |event: web_sys::KeyboardEvent| {
        if !event.ctrl_key() {
            return;
        }

        let key = event.key().to_ascii_lowercase();
        let redo = key == "y" || (key == "z" && event.shift_key());
        let undo = key == "z" && !event.shift_key();
        if !undo && !redo {
            return;
        }

        event.prevent_default();
        let changed = {
            let mut doc = document.borrow_mut();
            let mut history = history.borrow_mut();
            if redo {
                history.redo(&mut doc)
            } else {
                history.undo(&mut doc)
            }
        };

        if changed {
            {
                let doc = document.borrow();
                render::repaint_committed(&doc);
            }
            dirty.set(true);
        }
    }) as Box<dyn FnMut(web_sys::KeyboardEvent)>);
    let _ = window.add_event_listener_with_callback("keydown", closure.as_ref().unchecked_ref());
    closure.forget();
}

/// Synchronous `window.confirm` prompt for the discard-unsaved
/// flow on Open and New. Returns `true` if the user accepted.
fn confirm_discard(message: &str) -> bool {
    web_sys::window()
        .and_then(|w| w.confirm_with_message(message).ok())
        .unwrap_or(false)
}

/// Convert persistence failures into concise status text for the toolbar.
fn persist_error_message(operation: &str, err: PersistError) -> String {
    match err {
        PersistError::Cancelled => String::new(),
        PersistError::Document(DocumentError::InvalidJson(err)) => {
            format!("{operation} failed: invalid JSON ({err})")
        }
        PersistError::Document(DocumentError::UnsupportedSchema(schema)) => {
            format!("{operation} failed: unsupported schema version: {schema}")
        }
        PersistError::Js(message) if is_blocked_file_write_message(&message) => {
            format!(
                "{operation} failed: this browser context blocks file writes. Open Stroke in Chrome or Edge instead of VS Code Simple Browser."
            )
        }
        PersistError::Js(message) => format!("{operation} failed: {message}"),
    }
}

/// VS Code Simple Browser and other embedded browser contexts may expose enough
/// of the File System Access API to show a picker, then reject `createWritable`.
/// Surface that as an environment limitation instead of a mysterious save bug.
fn is_blocked_file_write_message(message: &str) -> bool {
    message.contains("createWritable")
        || message.contains("not allowed by the user agent")
        || message.contains("platform in the current context")
}
